import test from 'node:test';import assert from 'node:assert/strict';
import fs from 'node:fs';
import {HistorySession} from '../src/session.mjs';import {RequestCoordinator} from '../src/coordinator.mjs';
import {DEFAULT_SETTINGS} from '../src/settings.mjs';import {watch,comment,KEY} from './fixtures.mjs';
const file=new URL('../src/controller.mjs',import.meta.url);
const module=fs.existsSync(file)?await import(file):{};
function preferences(enabled=true,settings={}){let state={enabled,settings:{...DEFAULT_SETTINGS,maxAdditionalComments:2,...settings}};const listeners=new Set();return {get:()=>state,subscribe:f=>(listeners.add(f),()=>listeners.delete(f)),setEnabled:v=>{state={...state,enabled:v};for(const f of listeners)f(state);}};}
function normal(videoId='sm1') {const nv=watch(videoId).data.response.$watchV4.data.comment.nvComment;return {generation:'play-'+videoId,videoInfo:{videoId,contextWatchId:videoId,duration:100,msgInfo:{videoId,nvComment:nv,threads:[{id:'10',fork:1,forkLabel:'owner',label:'owner',layer:{index:0}},{id:'10',fork:0,forkLabel:'main',label:'default',layer:{index:0}}]}},result:{format:'threads',threadInfo:{videoId,threadId:'10',language:'ja-jp',isWaybackMode:false},body:{threads:[{id:'10',fork:'owner',commentCount:0,comments:[]},{id:'10',fork:'main',commentCount:50,comments:[comment(9,1700000009)]}]}}};}
function make(options={}){assert.equal(typeof module.CommentHistoryController,'function');const calls=[],clears=[],notices=[],prefs=options.preferences??preferences();let clock=0;
 const controller=new module.CommentHistoryController({preferences:prefs,render:async(data,o)=>{assert(o.isCurrent());calls.push(data);return {additionalCount:data.threads.reduce((n,t)=>n+t.comments.length,0)};},clearRender:()=>clears.push(1),notify:m=>notices.push(m),createSession:(context,o)=>new HistorySession(context,{...o,coordinator:new RequestCoordinator({settings:o.settings,now:()=>clock,sleep:async n=>{clock+=n;}}),fetchPage:options.fetchPage??(async()=>[{id:'10',fork:'main',commentCount:50,comments:[comment(1,1700000001),comment(2,1700000002),comment(3,1700000003),comment(4,1700000004)]}])}),...options});return {controller,calls,clears,notices,prefs};}
test('disabled stays idle; enabling automatically starts after a normal load',async()=>{const h=make({preferences:preferences(false)});await h.controller.normalReady(normal());assert.equal(h.calls.length,0);h.prefs.setEnabled(true);await h.controller.whenIdle();assert.equal(h.calls.length,1);assert.equal(h.controller.state.phase,'ready');assert.equal(h.controller.state.additionalCount,2);});
test('completed history is applied once, and continuation increases the total by the configured step',async()=>{const h=make();await h.controller.normalReady(normal());assert.equal(h.calls.length,1);await h.controller.more();assert.equal(h.calls.length,2);assert.equal(h.controller.state.additionalCount,4);assert.equal(h.controller.state.goal,4);});
test('automatic continuation across videos clears old data and waits for new normal metadata',async()=>{const h=make();await h.controller.normalReady(normal('sm1'));h.controller.invalidate();assert.equal(h.controller.state.additionalCount,0);await h.controller.normalReady(normal('sm2'));assert.equal(h.calls.length,2);assert.equal(h.controller.state.videoId,'sm2');assert.equal(h.controller.state.enabled,true);});
test('OFF cancels obsolete work and late completion cannot reapply it',async()=>{let release;const h=make({fetchPage:()=>new Promise(r=>release=r)});const pending=h.controller.normalReady(normal());await new Promise(r=>setImmediate(r));h.prefs.setEnabled(false);release([{id:'10',fork:'main',commentCount:0,comments:[]}]);await pending;assert.equal(h.calls.length,0);assert.equal(h.controller.state.enabled,false);assert.equal(h.controller.state.additionalCount,0);});
test('manual stop keeps successful partial pages and leaves next-video auto mode enabled',async()=>{let count=0,release;const h=make({preferences:preferences(true,{maxAdditionalComments:5}),fetchPage:async()=>++count===1?[{id:'10',fork:'main',commentCount:10,comments:[comment(3,1700000003),comment(4,1700000004)]}]:new Promise(r=>release=r)});const pending=h.controller.normalReady(normal());while(!release)await new Promise(r=>setImmediate(r));h.controller.stop();await pending;assert.equal(h.calls.length,1);assert.equal(h.controller.state.additionalCount,2);assert.equal(h.controller.state.enabled,true);assert.equal(h.controller.state.phase,'partial');assert.equal(h.notices.length,0);release([]);});
test('failure uses valid partial result once and emits one notification',async()=>{let n=0;const h=make({preferences:preferences(true,{maxAdditionalComments:5}),fetchPage:async()=>{if(n++)throw Object.assign(new Error('sensitive'),{code:'API_ERROR'});return [{id:'10',fork:'main',commentCount:10,comments:[comment(3,1700000003),comment(4,1700000004)]}];}});await h.controller.normalReady(normal());assert.equal(h.calls.length,1);assert.equal(h.notices.length,1);assert.equal(h.controller.state.phase,'partial');const diagnostic=JSON.stringify(h.controller.state);for(const secret of [KEY,'SYNTHETIC_BODY','SYNTHETIC_USER','sensitive'])assert(!diagnostic.includes(secret));});
test('acquisition failures notify once without leaking the original error',async()=>{const h=make({acquire:async()=>{throw new Error('private lock failure');}});await h.controller.normalReady(normal());assert.equal(h.controller.state.reason,'operation_failed');assert.equal(h.notices.length,1);assert(!JSON.stringify(h.controller.state).includes('private lock failure'));});
