import test from 'node:test';import assert from 'node:assert/strict';
import {normalizeWatch,validateThreads,HistoryError} from '../src/core.mjs';import {collectHistory} from '../src/history.mjs';import {watch,comment,body} from './fixtures.mjs';
const ctx=()=>normalizeWatch(watch(),'sm1'),targets=[{id:'10',fork:'main'}];
const opts={targets,startWhen:1700000100,intervalMs:0,maxPages:5,maxComments:5000,maxElapsedMs:30000};
const page=(context,cs)=>validateThreads(body(cs),context,targets);
test('cursor uses oldest raw posting date, not position or first item',async()=>{const seen=[];let i=0;const r=await collectHistory(ctx(),{...opts,fetchPage:async(c,o)=>{seen.push(o.when);return page(c,i++===0?[comment(3,1700000003),comment(1,1700000001),comment(2,1700000002)]:[]);}});assert.deepEqual(seen,[1700000100,1700000001]);assert.equal(r.uniqueComments,3);assert.equal(r.reason,'empty_page');assert.equal(r.complete,false);});
test('overlapping pages keep different comments and remove real duplicates',async()=>{let i=0;const pages=[[comment(3,1700000003),comment(4,1700000004)],[comment(2,1700000002),comment(3,1700000003)],[]];const r=await collectHistory(ctx(),{...opts,fetchPage:async c=>page(c,pages[i++])});assert.equal(r.uniqueComments,3);assert.equal(r.duplicates,1);});
test('same-second stalled cursor stops without subtracting a second',async()=>{let calls=0;const r=await collectHistory(ctx(),{...opts,fetchPage:async c=>{calls++;return page(c,[comment(9,1700000009)]);}});assert.equal(calls,2);assert.equal(r.reason,'cursor_stalled');assert.equal(r.complete,false);});
test('strict successful-request page budget stops at configured cap',async()=>{let i=0;const r=await collectHistory(ctx(),{...opts,maxPages:2,fetchPage:async c=>page(c,[comment(++i,1700000090-i)])});assert.equal(r.requests,2);assert.equal(r.reason,'page_limit');});
test('strict unique-comment budget records truncation',async()=>{const r=await collectHistory(ctx(),{...opts,maxComments:1,fetchPage:async c=>page(c,[comment(1),comment(2)])});assert.equal(r.uniqueComments,1);assert.equal(r.reason,'comment_limit');assert.equal(r.complete,false);});
test('network failure retains earlier data but marks partial error',async()=>{let i=0;const r=await collectHistory(ctx(),{...opts,fetchPage:async c=>{if(i++)throw new HistoryError('RATE_LIMITED',{retryAfterMs:60000});return page(c,[comment(1)]);}});assert.equal(r.uniqueComments,1);assert.equal(r.reason,'rate_limited');assert.equal(r.error.retryAfterMs,60000);assert.equal(r.complete,false);});
test('cancellation prevents a late response from reaching the store',async()=>{const c=new AbortController();let resolve;const p=collectHistory(ctx(),{...opts,signal:c.signal,fetchPage:()=>new Promise(r=>{resolve=r;})});await new Promise(r=>setImmediate(r));c.abort();resolve(page(ctx(),[comment(1)]));const result=await p;assert.equal(result.uniqueComments,0);assert.equal(result.reason,'cancelled');});
test('elapsed-time budget works against a nonresponsive transport',async()=>{const r=await collectHistory(ctx(),{...opts,maxElapsedMs:15,fetchPage:()=>new Promise(()=>{})});assert.equal(r.reason,'time_limit');assert.equal(r.uniqueComments,0);});
test('wrong target in a transport result is rejected',async()=>{const r=await collectHistory(ctx(),{...opts,fetchPage:async()=>[{id:'99',fork:'main',commentCount:1,comments:[comment(1)]}]});assert.equal(r.reason,'target_not_allowed');assert.equal(r.uniqueComments,0);});
test('invalid configuration is rejected before network',async()=>{await assert.rejects(()=>collectHistory(ctx(),{...opts,maxPages:0}),e=>e.code==='OPTION');});
test('progress callbacks receive aggregate counts, not raw data or keys',async()=>{const seen=[];const r=await collectHistory(ctx(),{...opts,maxPages:1,onProgress:x=>seen.push(x),fetchPage:async c=>page(c,[comment(1)])});const text=JSON.stringify(seen);assert.equal(r.uniqueComments,1);assert(!text.includes('SYNTHETIC_BODY'));assert(!text.includes('SECRET'));assert(!JSON.stringify(r).includes('SYNTHETIC_TEST_SECRET'));});
test('per-request timeout is distinguished from the entire-job time budget',async()=>{const r=await collectHistory(ctx(),{...opts,fetchPage:async()=>{throw new HistoryError('TIMEOUT');}});assert.equal(r.reason,'request_timeout');});
test('unverified sub-second boundaries stop without rounding past unseen data',async()=>{const r=await collectHistory(ctx(),{...opts,fetchPage:async c=>page(c,[comment(1,1700000000.5)])});assert.equal(r.reason,'subsecond_boundary_unverified');assert.equal(r.requests,1);assert.equal(r.complete,false);});
test('job deadline cause is explicit even when wall clock has not advanced',async()=>{
 const original=Date.now;Date.now=()=>1700000000000;
 try {const r=await collectHistory(ctx(),{...opts,maxElapsedMs:15,fetchPage:()=>new Promise(()=>{})});assert.equal(r.reason,'time_limit');}
 finally {Date.now=original;}
});
