import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const url=new URL('../src/browser-preferences.mjs',import.meta.url);const module=fs.existsSync(url)?await import(url):{};
function environment(map=new Map()){const events=new EventTarget();let writes=0;const storage={getItem:k=>map.get(k)??null,setItem:(k,v)=>{writes++;map.set(k,String(v));},removeItem:k=>{writes++;map.delete(k);}};return {window:{addEventListener:events.addEventListener.bind(events),removeEventListener:events.removeEventListener.bind(events),dispatchEvent:events.dispatchEvent.bind(events),CustomEvent,localStorage:storage},storage,map,writes:()=>writes};}
function make(env,config){assert.equal(typeof module.createBrowserHistoryPreferences,'function');return module.createBrowserHistoryPreferences({window:env.window,config});}
test('preferences start OFF at 5000 and keep enabled across a new instance',()=>{const env=environment();const p=make(env);assert.equal(p.get().enabled,false);assert.equal(p.get().settings.maxAdditionalComments,5000);p.setEnabled(true);const q=make(env);assert.equal(q.get().enabled,true);p.dispose();q.dispose();});
test('same-page adapters share feature changes without touching volume or rewriting notifications',()=>{const env=environment(new Map([['ZenzaWatch_volume','0.3']]));const a=make(env),b=make(env);let updates=0;b.subscribe(()=>updates++);a.patch({maxAdditionalComments:10000});assert.equal(b.get().settings.maxAdditionalComments,10000);assert.equal(env.writes(),1);assert.equal(env.map.get('ZenzaWatch_volume'),'0.3');assert.equal(updates,1);a.dispose();b.dispose();});
test('external storage refresh accepts deletion as default and synchronizes memory without persistence',()=>{const env=environment();const config={default:{'commentHistory.maxAdditionalComments':5000,'commentHistory.enabled':false},_data:{'commentHistory.maxAdditionalComments':10000},emit(){}};const p=make(env,config);env.map.set('ZenzaWatch_commentHistory.maxAdditionalComments','20000');const event=new Event('storage');Object.defineProperty(event,'key',{value:'ZenzaWatch_commentHistory.maxAdditionalComments'});env.window.dispatchEvent(event);assert.equal(config._data['commentHistory.maxAdditionalComments'],20000);assert.equal(env.writes(),0);env.map.delete('ZenzaWatch_commentHistory.maxAdditionalComments');env.window.dispatchEvent(event);assert.equal(p.get().settings.maxAdditionalComments,5000);assert.equal(config._data['commentHistory.maxAdditionalComments'],5000);p.dispose();});
test('invalid storage is reported without silent overwrite or automatic start',()=>{const env=environment(new Map([['ZenzaWatch_commentHistory.enabled','"yes"']]));const p=make(env);assert.equal(p.get().valid,false);assert.equal(p.get().enabled,false);assert.equal(env.writes(),0);assert.throws(()=>p.setEnabled(true));assert.equal(env.writes(),0);p.dispose();});
test('only valid presets/ranges are stored and Config.import is never used',()=>{const env=environment();const p=make(env,{import(){throw new Error('wrong API');}});assert.throws(()=>p.patch({maxAdditionalComments:20001}));assert.throws(()=>p.patch({volume:1}));assert.equal(env.writes(),0);p.patch({includeEasy:true});assert.equal(p.get().settings.includeEasy,true);p.dispose();});
