/** Restricted, deterministic generator for OUR checked-in named-export modules.
 * Not a general ESM bundler: aliases, re-exports, default imports, cycles, dynamic
 * imports and imports outside src are rejected. Generated files are Zenza
 * BEGIN/END script sections with an ESM wrapper outside the build region.
 */
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
const packageRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const identifier=/^[A-Za-z_$][\w$]*$/;
const moduleName=/^[a-z][a-z0-9-]*\.mjs$/;
const hash=text=>crypto.createHash('sha256').update(text).digest('hex');
export const ZENZA_BUNDLES=Object.freeze([
  Object.freeze({namespace:'ZenzaCommentHistoryCore',entries:Object.freeze(['core.mjs','coordinator.mjs','session.mjs','zenza-context.mjs','controller.mjs','renderer.mjs','panel.mjs','browser-preferences.mjs']),file:'ZenzaCommentHistoryCore.generated.js'}),
  Object.freeze({namespace:'ZenzaCommentHistorySettings',entries:Object.freeze(['settings.mjs','zenza-settings.mjs','browser-preferences.mjs','panel.mjs']),file:'ZenzaCommentHistorySettings.generated.js'})
]);
function readGraph(sourceDir,entries){
  const root=fs.realpathSync(sourceDir),modules=new Map(),visiting=new Set();
  function visit(name){
    if(!moduleName.test(name))throw new Error('Unsupported module path: '+name);
    if(visiting.has(name))throw new Error('Cyclic module dependency: '+name);
    if(modules.has(name))return modules.get(name);
    const file=fs.realpathSync(path.join(root,name));
    if(path.dirname(file)!==root)throw new Error('Module escapes source root: '+name);
    const source=fs.readFileSync(file,'utf8');
    if(/\bimport\s*(?:\(|\.)/.test(source))throw new Error('Dynamic import/import.meta unsupported: '+name);
    if(source.includes('//===BEGIN===')||source.includes('//===END==='))throw new Error('Reserved section marker: '+name);
    const imports=[],exports=[];
    const body=source.replace(/\r\n/g,'\n').split('\n').map(line=>{
      if(/^\s*import\b/.test(line)){
        const match=line.match(/^\s*import\s*\{([^}]+)\}\s*from\s*['"]\.\/([a-z][a-z0-9-]*\.mjs)['"];?\s*$/);
        if(!match)throw new Error('Unsupported import syntax: '+name);
        const names=match[1].split(',').map(s=>s.trim());
        if(names.some(s=>!identifier.test(s))||new Set(names).size!==names.length)throw new Error('Unsupported imported names: '+name);
        imports.push({names,dependency:match[2]});return '';
      }
      if(/^\s*export\b/.test(line)){
        const match=line.match(/^export\s+(?:(?:async\s+)?function|class|const)\s+([A-Za-z_$][\w$]*)\b/);
        if(!match||exports.includes(match[1]))throw new Error('Unsupported export syntax: '+name);
        exports.push(match[1]);return line.replace(/^export\s+/,'');
      }
      return line;
    }).join('\n');
    visiting.add(name);
    for(const imported of imports){
      const dependency=visit(imported.dependency);
      if(imported.names.some(n=>!dependency.exports.includes(n)))throw new Error('Missing imported export: '+name);
    }
    // Syntax-check without executing module bodies. Unhandled static module syntax fails here.
    const bindings=imports.map(i=>`const {${i.names.join(',')}} = {};`).join('\n');
    new vm.Script(`(()=>{\n'use strict';\n${bindings}\n${body}\nreturn {${exports.join(',')}};\n})();`,{filename:name});
    const item={name,body,exports,imports,sha256:hash(source)};
    visiting.delete(name);modules.set(name,item);return item;
  }
  for(const entry of entries)visit(entry);
  return modules;
}
export function renderZenzaBundle({sourceDir,entries,namespace}={}){
  if(typeof sourceDir!=='string'||!Array.isArray(entries)||!entries.length||entries.some(e=>typeof e!=='string')||
      typeof namespace!=='string'||!identifier.test(namespace))throw new Error('Invalid generator options');
  const graph=readGraph(sourceDir,entries),names=[...graph.keys()],ids=new Map(names.map((n,i)=>[n,i]));
  const exported=new Map();
  for(const entry of new Set(entries))for(const name of graph.get(entry).exports){
    if(exported.has(name))throw new Error('Duplicate public export: '+name);
    exported.set(name,entry);
  }
  const sections=[
    '// Generated by tools/build-zenza.mjs. Edit src/*.mjs, not this file.',
    '// Build input hashes (source text, before transformation):',
    ...[...graph.values()].map(m=>`// ${m.name} sha256=${m.sha256}`),
    '//===BEGIN===',`const ${namespace} = (() => {`,"'use strict';",'const modules = [];'
  ];
  for(const m of graph.values()){
    sections.push(`// Module: ${m.name}`,`modules[${ids.get(m.name)}] = (() => {`);
    for(const i of m.imports)sections.push(`const {${i.names.join(',')}} = modules[${ids.get(i.dependency)}];`);
    sections.push(m.body,`return Object.freeze({${m.exports.join(',')}});`,'})();');
  }
  sections.push('return Object.freeze({',...[...exported].map(([name,entry])=>`${name}: modules[${ids.get(entry)}].${name},`),'});','})();','//===END===',`export {${namespace}};`,'');
  const code=sections.join('\n');
  const section=code.split('//===BEGIN===')[1].split('//===END===')[0];
  new vm.Script(section,{filename:namespace+'.generated.js'});return code;
}
function generate(check){
  const folder=path.join(packageRoot,'src','generated');
  // Render EVERYTHING before any write; unsupported source leaves old artifacts unchanged.
  const outputs=ZENZA_BUNDLES.map(def=>({file:def.file,code:renderZenzaBundle({sourceDir:path.join(packageRoot,'src'),...def})}));
  outputs.push({file:'package.json',code:JSON.stringify({type:'module'},null,2)+'\n'});
  const manifest={schema:'nico-comment-history-zenza-generated/1',generatorVersion:2,
    files:outputs.map(o=>({path:o.file,sha256:hash(o.code),bytes:Buffer.byteLength(o.code)}))};
  outputs.push({file:'MANIFEST.json',code:JSON.stringify(manifest,null,2)+'\n'});
  if(check){
    for(const o of outputs)if(!fs.existsSync(path.join(folder,o.file))||fs.readFileSync(path.join(folder,o.file),'utf8')!==o.code)throw new Error('Generated artifact differs: '+o.file);
    console.log('Generated artifacts match: '+outputs.length);return;
  }
  fs.mkdirSync(folder,{recursive:true});
  for(const o of outputs){
    const dest=path.join(folder,o.file),temp=dest+'.tmp-'+process.pid;
    try{fs.writeFileSync(temp,o.code,{flag:'wx'});fs.renameSync(temp,dest);}finally{if(fs.existsSync(temp))fs.unlinkSync(temp);}
  }
  console.log('Generated '+outputs.length+' artifacts.');
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){
  try{
    const args=process.argv.slice(2);
    if(args.some(a=>a!=='--check')||args.length>1)throw new Error('Usage: node tools/build-zenza.mjs [--check]');
    generate(args.includes('--check'));
  }catch(error){console.error(error.message);process.exitCode=1;}
}
