const assert=require('assert');const {extract,createContext,run}=require('../helpers/extractSource');
const ticks=async()=>{for(let i=0;i<20;i++)await Promise.resolve();};
function setup(){const draws=[],node=()=>({style:{},childNodes:[],append(){}}),parts={'.scHeader':node(),'.scBanners':node()};
const c=createContext({performance:{now:()=>0},AbortController,CANVAS_W:1280,CANVAS_H:720,DEFAULT_BG:'#00f',MAX_DURATION:30,DEFAULT_DURATION:11.5,SupportersPage:class{},setInterval:()=>1,clearInterval(){},setTimeout:()=>1,requestAnimationFrame:()=>1,cancelAnimationFrame(){},document:{createElement:()=>({width:0,height:0,getContext:()=>({fillRect(){},drawImage(...a){draws.push(a);}})})}});
run(extract('packages/zenza/src/videoPlayer/SupporterCredit.js','CreditView')+';this.CreditView=CreditView;',c);const v=new c.CreditView({parentNode:{}});v._initializeDom=()=>{};v.view={querySelector:n=>parts[n],classList:{add(){},remove(){}}};return {v,draws};}
const data=position=>({supporters:{adTopSupporter:{auxiliary:{bgVideoPosition:position,bgColor:'#123'}}},gifts:[]});
describe('Supporter credit selected background (Task171)',()=>{
 [0,56].forEach(sec=>it(`captures the requested ${sec}-second frame without blocking prepare`,async()=>{const h=setup(),calls=[];let resolve;await h.v.prepare(data(sec),{captureBackground:(...a)=>{calls.push(a);return new Promise(r=>resolve=r);}});await ticks();assert.equal(calls.length,1);assert.equal(calls[0][0],sec);assert(calls[0][1]);assert.equal(h.v.isReady,true);resolve({width:640,height:360});await h.v._backgroundLoading;assert.equal(h.draws.length,1);assert(h.v.bgCanvas);assert.equal(h.draws[0][3],1280);assert.equal(h.draws[0][4],720);}));
 it('does not substitute the final main-player frame at start',async()=>{const h=setup();await h.v.prepare(data(56),{captureBackground:async()=>({width:640,height:360})});await h.v._backgroundLoading;const saved=h.v.bgCanvas;assert(saved);h.v.start({videoElement:{videoWidth:640,videoHeight:360}});assert.equal(h.v.bgCanvas,saved);assert.equal(h.draws.length,1);h.v.stop();});
 it('cancels pending capture on dispose and ignores a late canvas',async()=>{const h=setup();let resolve,signal;await h.v.prepare(data(1),{captureBackground:(s,a)=>{signal=a;return new Promise(r=>resolve=r);}});await ticks();h.v.dispose();assert(signal.aborted);resolve({width:10,height:10});await ticks();assert.equal(h.v.bgCanvas,null);});
 it('does not let an earlier preparation replace a newer background',async()=>{const h=setup();let resolve;await h.v.prepare(data(1),{captureBackground:()=>new Promise(r=>resolve=r)});await ticks();await h.v.prepare(data(2),{captureBackground:async()=>({width:20,height:20})});await h.v._backgroundLoading;const saved=h.v.bgCanvas;resolve({width:10,height:10});await ticks();assert.equal(h.v.bgCanvas,saved);assert.equal(h.draws.length,1);});
 it('uses the configured color when capture fails',async()=>{const h=setup();await h.v.prepare(data(3),{captureBackground:async()=>{throw Error('unavailable');}});await h.v._backgroundLoading;assert.equal(h.v.bgCanvas,null);assert.equal(h.v.bgColor,'#123');assert.equal(h.v.isReady,true);});
 it('propagates external cancellation and ignores its late result',async()=>{const h=setup(),abort=new AbortController();let resolve,signal;await h.v.prepare(data(1),{signal:abort.signal,captureBackground:(s,a)=>{signal=a;return new Promise(r=>resolve=r);}});await ticks();abort.abort();assert(signal.aborted);resolve({width:10,height:10});await ticks();assert.equal(h.v.bgCanvas,null);});
 it('rejects non-finite or negative positions without making captures',async()=>{for(const sec of [NaN,Infinity,-1]){const h=setup();let calls=0;await h.v.prepare(data(sec),{captureBackground:async()=>{calls++;}});await ticks();assert.equal(calls,0);assert.equal(h.v.useVideoBackground,false);}});
 [0,56].forEach(sec=>it(`passes source and isolated capture to the credit at position ${sec}`,async()=>{
  const calls=[],record=data(sec),c=createContext({Emitter:class{},AbortController,SupporterCredit:{load:async()=>record},VideoCaptureUtil:{capture:async(...args)=>{calls.push(args);return {};}}});
  run(extract('src/NicoVideoPlayer.js','NicoVideoPlayer')+';this.Player=NicoVideoPlayer;',c);
  const player=Object.create(c.Player.prototype);player._creditRequest={videoId:'sm9',tags:[]};player._playerConfig={props:{'supporterCredit.gift':true}};player._videoPlayer={src:'https://media.example.test/fixture.m3u8',currentTime:20};
  player._supporterCredit={prepare:async(d,options)=>{assert.equal(d,record);assert.equal(options.signal,player._creditAbort.signal);await options.captureBackground(sec,options.signal);}};
  await player._kickSupporterCreditLoad();assert.equal(calls.length,1);assert.equal(calls[0][0],player._videoPlayer.src);assert.equal(calls[0][1],sec);assert.equal(calls[0][2].timeout,8000);assert.equal(player._videoPlayer.currentTime,20);assert.equal(player._creditData,record);
 }));

});
