const {assert,ticks,observe,eventTarget,controllerFixture}=require('../helpers/idbRecoveryFixture');
function fixture(){const timers=new Map();let id=0;const f=controllerFixture({setTimeout(fn){timers.set(++id,fn);return id;},clearTimeout(id){timers.delete(id);}});return {...f,timers};}
function database(version=1){return {version,closed:0,close(){this.closed++;},objectStoreNames:{contains:()=>true}};}
function success(f,index,db){f.opens[index].req.result=db;f.opens[index].req.fire('success');}
describe('IndexedDB connection and non-destructive upgrade lifetime (Task168)',()=>{
 it('blocked open rejects and closes its late success without caching it',async()=>{const f=fixture(),args={name:'fixture',ver:2,stores:[]},p=observe(f.controller.init(args));f.opens[0].req.fire('blocked');await ticks();assert.equal(p.status,'rejected');const late=database(2);success(f,0,late);assert.equal(late.closed,1);const next=f.controller.init(args);success(f,1,database(2));await next;assert.equal(f.timers.size,0);});
 it('silent open reaches a deadline and aborts a late upgrade',async()=>{const f=fixture(),p=observe(f.controller.init({name:'fixture',ver:1,stores:[]}));assert.equal(f.timers.size,1);[...f.timers.values()][0]();await ticks();assert.equal(p.status,'rejected');let aborted=0;f.opens[0].req.transaction={abort(){aborted++;}};f.opens[0].req.fire('upgradeneeded');assert.equal(aborted,1);});
 it('versionchange releases the old connection and reopens without forcing an old version',async()=>{const f=fixture(),db=database(1),p=f.controller.init({name:'fixture',ver:1,stores:[]});success(f,0,db);await p;assert.equal(typeof db.onversionchange,'function');db.onversionchange();assert.equal(db.closed,1);const q=f.controller.init({name:'fixture'});assert.equal(f.opens[1].version,undefined);const newDb=database(2);success(f,1,newDb);await q;db.onclose();assert.equal(await f.controller.init({name:'fixture'}),newDb);});
 it('explicitly requesting a newer version closes the cached handle and upgrades',async()=>{const f=fixture(),old=database(1),p=f.controller.init({name:'fixture',ver:1,stores:[]});success(f,0,old);await p;const q=f.controller.init({name:'fixture',ver:2,stores:[]});assert.equal(old.closed,1);assert.equal(f.opens[1].version,2);success(f,1,database(2));await q;});
 it('a different requested version waits for in-flight initialization then opens its version',async()=>{const f=fixture(),p=f.controller.init({name:'fixture',ver:1,stores:[]}),q=f.controller.init({name:'fixture',ver:2,stores:[]});success(f,0,database(1));await p;await ticks();assert.equal(f.opens.length,2);assert.equal(f.opens[1].version,2);success(f,1,database(2));await q;});
 it('closing an in-flight open rejects it and prevents a late handle from being cached',async()=>{const f=fixture(),p=observe(f.controller.init({name:'fixture',ver:1,stores:[]}));f.controller.close({name:'fixture'});await ticks();assert.equal(p.status,'rejected');const db=database();success(f,0,db);assert.equal(db.closed,1);});
 it('compatible upgrades preserve the store and add missing indexes only',async()=>{const f=fixture(),created=[],store={keyPath:'id',autoIncrement:false,indexNames:{contains:n=>n==='old'},createIndex(...a){created.push(a);},index(){return {keyPath:'id',unique:false,multiEntry:false};}},db=database();let deleted=0;db.deleteObjectStore=()=>deleted++;db.createObjectStore=()=>{throw Error('must retain store');};const reqArgs={name:'fixture',ver:2,stores:[{name:'records',definition:{keyPath:'id'},indexes:[{name:'old',keyPath:'id'},{name:'updatedAt',keyPath:'updatedAt'}]}]};const p=f.controller.init(reqArgs),req=f.opens[0].req;req.result=db;req.transaction={objectStore:()=>store,abort(){throw Error('unexpected abort');}};req.fire('upgradeneeded');success(f,0,db);await p;assert.equal(deleted,0);assert.equal(created.length,1);assert.equal(created[0][0],'updatedAt');});
 it('incompatible key-path changes reject and abort instead of deleting records',async()=>{const f=fixture();let deleted=0,aborted=0;const p=observe(f.controller.init({name:'fixture',ver:2,stores:[{name:'records',definition:{keyPath:'newId'}}]})),req=f.opens[0].req;req.result={objectStoreNames:{contains:()=>true},deleteObjectStore(){deleted++;},createObjectStore:()=>({transaction:{}})};req.transaction={objectStore:()=>({keyPath:'oldId',autoIncrement:false}),abort(){aborted++;}};req.fire('upgradeneeded');await ticks();assert.equal(p.status,'rejected');assert.equal(deleted,0);assert.equal(aborted,1);});
 it('changing an existing index definition aborts the upgrade',async()=>{const f=fixture();let aborted=0;const p=observe(f.controller.init({name:'fixture',ver:2,stores:[{name:'records',definition:{keyPath:'id'},indexes:[{name:'owner',keyPath:'newOwner'}]}]})),req=f.opens[0].req;req.result={objectStoreNames:{contains:()=>true},deleteObjectStore(){},createObjectStore:()=>({createIndex(){},transaction:{}})};req.transaction={objectStore:()=>({keyPath:'id',autoIncrement:false,indexNames:{contains:()=>true},index:()=>({keyPath:'oldOwner',unique:false,multiEntry:false})}),abort(){aborted++;}};req.fire('upgradeneeded');await ticks();assert.equal(p.status,'rejected');assert.equal(aborted,1);});
 [false,true].forEach(cached=>it(`reads wait for the newest connection when an upgrade supersedes ${cached?'cached':'pending'} init`,async()=>{
  const f=fixture(),old=database(1),fresh=database(2);
  old.transaction=()=>{if(old.closed)throw Error('closed connection');return {objectStore:()=>({version:1})};};
  fresh.transaction=()=>({objectStore:()=>({version:2})});
  const first=f.controller.init({name:'fixture',ver:1,stores:[]});
  let read,upgrade;
  if(cached){success(f,0,old);await first;read=observe(f.controller.getStore({name:'fixture',storeName:'records'}));upgrade=f.controller.init({name:'fixture',ver:2,stores:[]});}
  else {upgrade=f.controller.init({name:'fixture',ver:2,stores:[]});read=observe(f.controller.getStore({name:'fixture',storeName:'records'}));success(f,0,old);await first;}
  await ticks();assert.equal(read.status,'pending');success(f,1,fresh);await upgrade;await ticks();assert.equal(read.status,'resolved');assert.equal(read.value.store.version,2);
 }));

});
