const {assert,ticks,observe,deferred,eventTarget,controllerFixture,adapterFixture,gateFixture}=require('../helpers/idbRecoveryFixture');
async function setup(){const read=eventTarget(),write=eventTarget(),tx=eventTarget(),modes=[],puts=[];tx.abort=()=>{};const store={get:()=>read,index:()=>({get:()=>read}),put(record){puts.push(record);return write;}};tx.objectStore=()=>store;const f=controllerFixture();await f.ready({transaction(name,mode){modes.push(mode);return tx;}});return {c:f.controller,read,write,tx,modes,puts};}
describe('Atomic history updates',()=>{
 it('updates timestamps within the same readwrite transaction',async()=>{const h=await setup();const state=observe(h.c.updateTime({name:'fixture',storeName:'cache',data:{key:'sm9'}}));await ticks();h.read.result={watchId:'sm9',watchCount:4};h.read.fire('success');await ticks();assert.deepStrictEqual(h.modes,['readwrite']);assert.strictEqual(h.puts[0].watchCount,4);assert.strictEqual(state.status,'pending');h.write.fire('success');h.tx.fire('complete');await ticks();assert.strictEqual(state.status,'resolved');});
 it('merges with the record read by its own transaction and waits for commit',async()=>{const h=await setup();assert.strictEqual(typeof h.c.update,'function');const state=observe(h.c.update({name:'fixture',storeName:'cache',data:{key:'sm9',patch:{watchId:'sm9',updatedAt:3},increment:{watchCount:1},append:{comment:['new']},prepend:{resume:[{time:8}]},limits:{resume:2}}}));await ticks();h.read.result={watchId:'sm9',watchCount:5,comment:['concurrent'],resume:[{time:7},{time:6}],title:'preserved'};h.read.fire('success');await ticks();assert.strictEqual(h.puts[0].watchCount,6);assert.deepStrictEqual(Array.from(h.puts[0].comment),['concurrent','new']);assert.deepStrictEqual(Array.from(h.puts[0].resume,x=>x.time),[8,7]);assert.strictEqual(h.puts[0].title,'preserved');h.write.fire('success');await ticks();assert.strictEqual(state.status,'pending');h.tx.fire('complete');await ticks();assert.strictEqual(state.status,'resolved');assert.strictEqual(state.value.watchCount,6);});
 it('rejects a merged write that later aborts',async()=>{const h=await setup();const state=observe(h.c.update({name:'fixture',storeName:'cache',data:{key:'sm9',patch:{watchId:'sm9'}}}));await ticks();h.read.result={};h.read.fire('success');h.write.fire('success');h.tx.error=new Error('aborted');h.tx.fire('abort');await ticks();assert.strictEqual(state.status,'rejected');});
 it('does not create a missing record just to update its timestamp',async()=>{const h=await setup();const state=observe(h.c.updateTime({name:'fixture',storeName:'cache',data:{key:'missing'}}));await ticks();h.read.result=undefined;h.read.fire('success');h.tx.fire('complete');await ticks();assert.strictEqual(state.status,'resolved');assert.strictEqual(state.value,null);assert.strictEqual(h.puts.length,0);});
 it('sends watch changes as one operation without a separate read',async()=>{const done=deferred();let update;const a=adapterFixture('WatchInfoCacheDb',{get(){throw Error('separate read');},updateTime(){throw Error('separate read');},put(){throw Error('separate put');},update(data){update=data;return done.promise;}});const pending=observe(a.put('sm9',{watchCount:1,currentTime:12,comment:'new'}));await ticks();assert.strictEqual(pending.status,'pending');assert.strictEqual(update.increment.watchCount,1);assert.strictEqual(update.prepend.resume[0].time,12);assert.strictEqual(update.limits.resume,10);done.resolve({watchId:'sm9',watchCount:9});await ticks();assert.strictEqual(pending.value.watchCount,9);});
 it('bridges merged updates and acknowledges only their commit',async()=>{const done=deferred();let data;const h=gateFixture({open:async()=>({cache:{update(v){data=v;return done.promise;}}})});await h.send({command:'open',params:{name:'fixture',stores:[]}});const state=observe(h.send({command:'update',params:{name:'fixture',storeName:'cache',data:{key:'sm9',increment:{watchCount:1}}}},'merge'));await ticks();assert.strictEqual(h.posts.length,1);assert.strictEqual(data.key,'sm9');done.resolve({watchId:'sm9',watchCount:2});await ticks();assert.strictEqual(state.status,'resolved');assert.strictEqual(h.posts[1].body.params.watchCount,2);});
 it('rejects malformed list updates before putting a partial record',async()=>{const h=await setup();const state=observe(h.c.update({name:'fixture',storeName:'cache',data:{key:'sm9',patch:{watchId:'sm9'},append:{comment:'bad'}}}));await ticks();h.read.result={};h.read.fire('success');await ticks();assert.strictEqual(state.status,'rejected');assert.strictEqual(h.puts.length,0);});
});
