const assert=require('assert');
const {beginSection,createContext,run}=require('../helpers/extractSource');
function setup(){const listeners=new Map();const window={addEventListener(n,f){listeners.set(n,f);},removeEventListener(n,f){if(listeners.get(n)===f)listeners.delete(n);}};
 const c=createContext({window});run(beginSection('packages/lib/src/Emitter.js'),c);run(beginSection('packages/lib/src/infra/Observable.js')+';this.O=Observable;',c);return {O:c.O,window,listeners};}
describe('Observable synchronous delivery and lifetime',()=>{
 it('delivers synchronous values and completion before returning',()=>{const {O}=setup(),values=[];let completed=0;const s=O.of(1,2).subscribe(v=>values.push(v),null,()=>completed++);assert.deepStrictEqual(values,[1,2]);assert.strictEqual(completed,1);assert(s.closed);});
 it('installs chained filters and maps before synchronous emission',()=>{const {O}=setup(),values=[];O.of(1,2,3).filter(v=>v>1).map(v=>v*2).subscribe(v=>values.push(v));assert.deepStrictEqual(values,[4,6]);});
 it('cleans a synchronous completion producer exactly once',()=>{const {O}=setup();let cleaned=0;const o=new O(s=>{s.complete();return ()=>cleaned++;});const a=o.subscribe(()=>{});a.unsubscribe();a.unsubscribe();assert.strictEqual(cleaned,1);});
 it('shares a producer until the last subscriber leaves',()=>{const {O}=setup();let starts=0,stops=0,source;const o=new O(s=>{starts++;source=s;return ()=>stops++;}),a=[],b=[];const sa=o.subscribe(v=>a.push(v)),sb=o.subscribe(v=>b.push(v));source.next(1);sa.unsubscribe();source.next(2);assert.deepStrictEqual(a,[1]);assert.deepStrictEqual(b,[1,2]);assert.strictEqual(starts,1);assert.strictEqual(stops,0);sb.unsubscribe();assert.strictEqual(stops,1);});
 it('reconnects after the last unsubscribe without reviving older subscriptions',()=>{const {O}=setup();const sources=[],values=[];let stops=0;const o=new O(s=>{sources.push(s);return ()=>stops++;});const a=o.subscribe(v=>values.push(v));a.unsubscribe();const b=o.subscribe(v=>values.push(v));sources[0].next('old');sources[1].next('new');assert.deepStrictEqual(values,['new']);assert(a.closed);assert(!b.closed);a.unsubscribe();assert.strictEqual(stops,1);b.unsubscribe();assert.strictEqual(stops,2);});
 it('runs a new synchronous sequence for a later subscriber',()=>{const {O}=setup(),values=[];const o=O.of(1);o.subscribe(v=>values.push(v));o.subscribe(v=>values.push(v));assert.deepStrictEqual(values,[1,1]);});
 it('ends and cleans on producer error, blocking later signals',()=>{const {O}=setup();let source,stops=0,errors=0;const values=[];const o=new O(s=>{source=s;return ()=>stops++;});const sub=o.subscribe(v=>values.push(v),()=>errors++);source.error(new Error('bad'));source.next(1);source.error(new Error('late'));assert(sub.closed);assert.strictEqual(stops,1);assert.strictEqual(errors,1);assert.deepStrictEqual(values,[]);});
 it('does not start twice on a subscription created from synchronous next',()=>{const {O}=setup();let starts=0;const o=new O(s=>{starts++;s.next(1);return ()=>{};});let child;const a=o.subscribe(()=>{child=o.subscribe(()=>{});});assert.strictEqual(starts,1);a.unsubscribe();child.unsubscribe();});
 it('can unsubscribe in start before producer work begins',()=>{const {O}=setup();let starts=0;const o=new O(()=>{starts++;return ()=>{};});const sub=o.subscribe({start(s){s.unsubscribe();}});assert(sub.closed);assert.strictEqual(starts,0);});
 it('executes concat sources once in order and cleans all producers',()=>{const {O}=setup();const values=[];let done=0;O.of(1,2).concat(O.of(3)).concat([4]).subscribe(v=>values.push(v),null,()=>done++);assert.deepStrictEqual(values,[1,2,3,4]);assert.strictEqual(done,1);});
 it('unsubscribes the active concatenated source',()=>{const {O}=setup();let source,stops=0;const tail=new O(s=>{source=s;return ()=>stops++;});const values=[];const sub=O.of(1).concat(tail).subscribe(v=>values.push(v));sub.unsubscribe();source.next(2);assert.strictEqual(stops,1);assert.deepStrictEqual(values,[1]);});
 it('disconnects cached fromEvent and can subscribe again',()=>{const h=setup();const o=h.O.fromEvent(h.window,'click'),values=[];const a=o.subscribe(v=>values.push(v));const old=h.listeners.get('click');a.unsubscribe();assert(!h.listeners.has('click'));const b=o.subscribe(v=>values.push(v));old(1);h.listeners.get('click')(2);assert.deepStrictEqual(values,[2]);b.unsubscribe();});
 it('rejects direct and indirect concat cycles before starting',()=>{const {O}=setup();const a=O.of(1),b=O.of(2);assert.throws(()=>a.concat(a));a.concat(b);assert.throws(()=>b.concat(a));});
 it('can subscribe again from a completion callback without sharing old cleanup',()=>{const {O}=setup();let stopped=0,completed=0;const values=[];const o=new O(s=>{s.next(1);s.complete();return ()=>stopped++;});o.subscribe(v=>values.push(v),null,()=>{completed++;o.subscribe(v=>values.push(v));});assert.deepStrictEqual(values,[1,1]);assert.strictEqual(stopped,2);assert.strictEqual(completed,1);});
});
it('preserves explicit producer start and completion payloads',()=>{const {O}=setup();let source,complete;const starts=[];const o=new O(s=>{source=s;return ()=>{};});o.subscribe({start(v){if(typeof v==='string')starts.push(v);},complete(v){complete=v;}});source.start('start');source.complete('done');assert.deepStrictEqual(starts,['start']);assert.strictEqual(complete,'done');});
